version: '3.8'

networks:
  projeto2_net:
    driver: bridge

volumes:
  postgresql:

services:
  # server:
  #   image: app
  #   build: .
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  #   ports:
  #     -  ${API_PORT}:${API_PORT}
  #   networks:
  #     - projeto2_net
  #   depends_on:
  #     - db
  #   command: ["yarn", "dev"]
  #   restart: always
  db: 
    image: postgres:10
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks: 
      - projeto2_net
    ports:
      - ${DB_PORT}:5432